services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    environment:
      - PROD='1'
    ports: 
      - "3000:3000"
    
    secrets:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
secrets:
  AWS_ACCESS_KEY_ID:
    file: ./run/secrets/AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    file: ./run/secrets/AWS_SECRET_ACCESS_KEY
   

