services:
  portfolio-app:
    container_name: portfolio-container
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
       - CONNECTION_STRING
       - EMAIL_FROM
       - EMAIL_SERVER_HOST
       - EMAIL_SERVER_PASSWORD
       - EMAIL_SERVER_PORT
       - EMAIL_SERVER_USER
       - NEXTAUTH_SECRET
       - NEXTAUTH_URL #provide secrets inside the build because they are needed during Dockerfile image build process
    environment:
     - PROD='1'
    secrets:
    - CONNECTION_STRING #providing secrets after the image build because they are needed for access to the container
    - EMAIL_FROM
    - EMAIL_SERVER_HOST
    - EMAIL_SERVER_PASSWORD
    - EMAIL_SERVER_PORT
    - EMAIL_SERVER_USER
    - NEXTAUTH_SECRET
    - NEXTAUTH_URL
 
  
    ports:
      - '3000:3000'

secrets:
  CONNECTION_STRING:
    file: ./run/secrets/CONNECTION_STRING
  EMAIL_FROM:
    file: ./run/secrets/EMAIL_FROM
  EMAIL_SERVER_HOST:
    file: ./run/secrets/EMAIL_SERVER_HOST
  
  EMAIL_SERVER_PASSWORD:
    file: ./run/secrets/EMAIL_SERVER_PASSWORD
  
  EMAIL_SERVER_PORT:
    file: ./run/secrets/EMAIL_SERVER_PORT
  EMAIL_SERVER_USER:
    file: ./run/secrets/EMAIL_SERVER_USER
  NEXTAUTH_SECRET:
    file: ./run/secrets/NEXTAUTH_SECRET
  NEXTAUTH_URL:
    file: ./run/secrets/NEXTAUTH_URL

  


