#This is pre stage, to install local mongodb, run it on 27107 port (mongo port) and then mount `/data/db` folder on efs
# because mongo store its data in that folder by default, the data is persistant even if ecs is re-deployed, because
# data is mounted on efs separately from ecs task.
FROM ubuntu:24.04 AS mongorunner
RUN apt update && \
    apt-get install -y --no-install-recommends ca-certificates curl gnupg && \
    install -d -m 0755 /etc/apt/keyrings && \
    curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
    gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg \
    --dearmor && echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-8.0.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends mongodb-org

RUN mkdir -p '/data/db'

EXPOSE 27107
CMD ["mongod", "--bind_ip_all", "--dbpath", "/data/db"]