name: Deploy Workflow
on:
  workflow_run:
    workflows: [Main Workflow]
    types:
      - completed
jobs:
  deploy:
    environment: portfolio_env
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Set AWS Credintials'
        uses: aws-actions/configure-aws-credentials@v4
        
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - if: ${{github.event.workflow_run.conclusion=='success'}}
        run: echo "previous workflow has succeeded"
      - name: 'Deploy on Amplify'
        if: ${{github.ref == 'refs/heads/main'}}
        run: |
          echo "Deploying to Amplify Production..."
          JOBS=$(aws amplify list-jobs \
            --app-id ${{ secrets.APP_ID }} \
            --branch-name main \
            --query "jobSummaries[?jobStatus=='PENDING' || jobStatus=='RUNNING']" \
            --output json)
      
          echo "Running jobs: $JOBS"
      
          if [ "$JOBS" == "[]" ]; then
            aws amplify start-job \
              --app-id ${{ secrets.APP_ID }} \
              --branch-name main \
              --job-type RELEASE
            echo "status=triggered" >> $GITHUB_OUTPUT
          else
            echo "Amplify job already running. Skipping deploy."
            echo "status=skipped" >> $GITHUB_OUTPUT
            exit 0
          fi
      - if: ${{github.event.workflow_run.conclusion == 'fail'}}
        run: |
          exit 1
          echo "An error occured at the build or test stage, check 'workflow.yml' logs for more info. "

      


        


