name: ondispatch

on:
  workflow_dispatch:
    inputs:
      deploymentStatus:
        description: 'Receive deployment status from Lambda function'
        required: true
        default: 'PENDING'

jobs:
  DEPLOYMENT_STATUS:
    runs-on: ubuntu-latest
    steps:
      - name: Check Deployment Status
        run: |
          echo "Received deploymentStatus: ${{ inputs.deploymentStatus }}"
          if [[ "${{ inputs.deploymentStatus }}" == "SUCCEED" ]]; then
            echo "Deployment Succeeded"
            exit 0
          elif [[ "${{ inputs.deploymentStatus }}" == "FAILED" ]]; then
            echo "Deployment failed, check AWS CloudWatch logs"
            exit 1
          else
            echo "Deployment status: ${{ inputs.deploymentStatus }}"
            exit 2
          fi

      - name: Log Deployment Status
        run: echo 'Workflow done. The website has been deployed and is ready.'
