name: Main Workflow

on:
  push:
    branches:

      - main
      - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: portfolio_env
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Download Dependencies
        run: npm i
      - name: Debug ENV variables secrets (TO BE DELETED)
        run: echo ${{secrets.CONNECTION_STRING}}
        env:
          CONNECTION_STRING: "${{ secrets.CONNECTION_STRING }}"

      - name: Build App
        env:
          CONNECTION_STRING: "${{ secrets.CONNECTION_STRING }}"
          NEXTAUTH_URL: "${{ secrets.NEXTAUTH_URL || 'http://localhost:3000' }}"
          NEXTAUTH_SECRET: "${{secrets.NEXTAUTH_SECRET}}"
        run: npm run build
      - name: Configure AWS Credinitials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to Amplify
        id: deploy_test
        if: github.ref == 'ref/heads/test'
        run: |
          echo "Deploying to Amplify Beta..."
          JOBS=$(aws amplify list-jobs \
            --app-id ${{ secrets.APP_ID }} \
            --branch-name test \
            --query "jobSummaries[?jobStatus=='PENDING' || jobStatus=='RUNNING']" \
            --output json)

           if [[ $JOBS == "[]" ]]; then
            aws amplify start-job \
              --app-id ${{ secrets.APP_ID}} \
              --branch-name test \
              --job-type RELEASE
            echo "status=triggered" >> $GITHUB_OUTPUT
          else
            echo "Amplify job already running. Skipping."
            echo "status=skipped" >> $GITHUB_OUTPUT
            exit 0
          fi
      - name: Deploy to Amplify (Production)
        id: deploy_prod
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to Amplify Production..."
          JOBS=$(aws amplify list-jobs \
            --app-id ${{ secrets.APP_ID}} \
            --branch-name main \
            --query "jobSummaries[?jobStatus=='PENDING' || jobStatus=='RUNNING']" \
            --output json)
          if [[ $JOBS == "[]" ]]; then
            aws amplify start-job \
              --app-id ${{ secrets.APP_ID}} \
              --branch-name main \
              --job-type RELEASE
            echo "status=triggered" >> $GITHUB_OUTPUT
          else
            echo "Amplify job already running. Skipping."
            echo "status=skipped" >> $GITHUB_OUTPUT
            exit 0
          fi
      - name: Log Succession
        run: echo "App has been deployed successfuly"
