name: Main Workflow

on:
  push:
    branches:

      - main
      - test
jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Code Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Install Dependencies'
        run: 'npm ci'

      - name: 'Test Code'
        run: 'npm run test'
  deploy_to_amplify:
    runs-on: ubuntu-latest
    environment: portfolio_env
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Download Dependencies
        run: npm i
      - name: Build App
        env:
          CONNECTION_STRING: "${{ secrets.CONNECTION_STRING }}"
          NEXTAUTH_URL: "${{ secrets.NEXTAUTH_URL || 'http://localhost:3000' }}"
          NEXTAUTH_SECRET: "${{secrets.NEXTAUTH_SECRET}}"
        run: npm run build
      - name: Configure AWS Credinitials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  